#! /bin/sh

# Set Keymap
setxkbmap de &

# Shortcuts
sxhkd &

# Background
#feh --bg-scale /home/user/Bilder/Wallpaper.png &

# Compositor
#picom &

# Polybar
#polybar white &

#bspc monitor eDP-1 -d
#bspc monitor DP-1-1 -d
#bspc monitor DP-1-2 -d

bspc monitor DP-1-1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DP-1-2 -d 1 2 3 4 5 6 7 8 9 10
if [-n xrandr | grep -e 'eDP-1' | grep 'connected .*x.* (']; then
  echo test
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
spc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


bspc config focused_border_color  '#f9d72d'

bspc rule -a feh state=floating
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
